recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    delete_all_shopping_items,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingItemsListView,
    create_shopping_item,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path(
        "shopping_items/create/",
        create_shopping_item,
        name="shopping_items_create",
    ),
    path(
        "shopping_items/list",
        ShoppingItemsListView.as_view(),
        name="shopping_items_list",
    ),
    path(
        "shopping_items/delete/",
        delete_all_shopping_items,
        name="delete_all_shopping_items",
    ),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItems(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_items", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

recipes/forms.py
from django import forms
from meal_plans.models import MealPlans
from django.forms import ModelForm

from recipes.models import Recipe
from recipes.models import Rating


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "author",
            "description",
            "image",
        ]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]


class DateInput(forms.DateInput):
    input_type = "date"


class CalendarForm(ModelForm):
    class Meta:
        model = MealPlans
        fields = ["name", "date", "recipes"]
        widgets = {
            "date": DateInput(),
        }


class ShoppingForm(forms.ModelForm):
    pass

recipes/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from recipes.forms import RatingForm
from .models import Ingredient
from django.db import IntegrityError
from django.views.decorators.http import require_http_methods

# from recipes.forms import RecipeForm
from recipes.models import Recipe, ShoppingItems

# I know having the comments in the code makes it look like
# I copy/pasted from the learn, but I actually just typed it in
# there for notation


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            try:
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
            except Recipe.DoesNotExist:
                return redirect("recipes_list")
    return redirect("recipe_detail", pk=recipe_id)


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        # Create a new empty list and assign it to a variable
        added_shopping_items = []

        # For each item in the user's shopping items, which we
        # can access through the code self.request.user.shopping_items.all
        for shopping_item in self.request.user.shopping_items.all():
            added_shopping_items.append(shopping_item)

        # Put that list into the context
        context["food_in_shopping_list"] = added_shopping_items
        return context


# all need a login.mixin
class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = [
        "name",
        "description",
        "image",
    ]
    success_url = reverse_lazy("recipes_list")
    login_url = "/login/"
    redirect_field_name = "recipe_list"
    LOGIN_REDIRECT_URL = "recipes_list"
    LOGOUT_REDIRECT_URL = "recipes_list"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = [
        "name",
        "author",
        "description",
        "image",
    ]
    success_url = reverse_lazy("recipes_list")
    login_url = "/login/"
    redirect_field_name = "recipe_list"
    LOGIN_REDIRECT_URL = "recipes_list"
    LOGOUT_REDIRECT_URL = "recipes_list"


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")
    login_url = "/login/"
    redirect_field_name = "recipes_list"
    LOGIN_REDIRECT_URL = "recipes_list"
    LOGOUT_REDIRECT_URL = "recipes_list"


# This view will show a list of shopping items that was created by the user.
class ShoppingItemsListView(ListView):
    model = ShoppingItems
    template_name = "shopping_items/list.html"


class ShoppingItemsCreateView(CreateView):
    model = ShoppingItems
    template_name = "shopping_items/create.html"
    fields = ["user", "food_item"]

    def get_queryset(self):
        return RecipeDetailView.objects.filer().get_queryset()


@require_http_methods(["POST"])
def delete_all_shopping_items(request):
    # Delete all of the shopping items for the user
    ShoppingItems.objects.filter(user=request.user).delete()

    return redirect("shopping_items_list")


# class CreateShoppingItem(Model):


@require_http_methods(["POST"])
def create_shopping_item(request):
    # Get the ingredient_id from the POST
    ingredient_id = request.POST.get("ingredient_id")
    # Get the specific ingredient from the Ingredient model
    ingredient = Ingredient.objects.get(id=ingredient_id)
    # Get the current user
    user = request.user

    # class Meta:
    #     unique_together = (("key1", "key2"),)

    # key1 = models.IntegerField(primary_key=True)
    # key2 = models.IntegerField()

    try:
        # Create the new shopping item in the database
        ShoppingItems.objects.create(
            food_item=ingredient.food,
            user=user,
        )
    # Catch the error if its already in there
    except IntegrityError:
        pass
    # Go back to the recipe page
    return redirect("recipe_detail", pk=ingredient.recipe.id)

recipes/templates/shopping_items/create.html
{% extends 'base.html' %} 

{% for ingredient in recipe.ingredients.all %}
    <tr>
        <td>{{ ingredient.amount }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food.name }}</td>

        <td>
            {% if ingredient.food not in food_in_shopping_list %}
            <form method="POST" action="{% url 'shopping_item_create' %}">
            {% crsf_token %}
            <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
            <button>+ shopping list</button>
            </form>
            {% endif %}
        </td>
    </tr>
{% endfor %}

recipes/templates/shopping_items/list.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>

  <body>
    <header>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </header>
    <main>
      <h1> "Your shopping list" </h1>
      <div>
      <form method = "post" action="{% url 'delete_all_shopping_items' %}">
        {% csrf_token %}
          <button class="button">Delete all</button>
        </form>
        <div>
        {% for ingredient in recipe.ingredients.all %}
          <tr>
            <td>{{ ingredient.amount }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
        
            <td>
              {% if ingredient.food not in shoppingitems_list %}
                <form method="POST" action="{% url 'shopping_items_create' %}">
                  {% csrf_token %}
                  <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                  <button>+ shopping list</button>
                </form>
              {% else %}
                in your list
              {% endif %}
            </td>
          
          </tr>
        {% endfor %}
        </div>
      </div>
      <div>
        <ul> 
          {% for item in shopping_items_list %}
          <a href="{% url 'ingredient_detail' ingredient.pk %}">{{ ingredient.name }}</a>
          <li> {{ item.food_item.name }} </li>
          {% endfor %}
        </ul>
      </div>
    </main>
  </body>
</html>
{% endblock %} 